MvcWebRole/Models/Job.cs
using Microsoft.WindowsAzure.Storage.Table;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MvcWebRole.Models
{
    public class Job : TableEntity
    {

        public Job()
        {
            this.PartitionKey = "USER:NOUSER";
            this.RowKey = "JOB:" + Guid.NewGuid().ToString();
        }


        [Required]
        [Display(Name="ID")]
        public string Id
        {
            get { return RowKey;  }
        }

        [Display(Name = "Template")]
        public string Template { get; set; }
        
        [Display(Name = "Data")]
        public string Data { get; set; }

        [Display(Name = "Owner")]
        public string Owner { get; set; }

        [Display(Name = "Start time")]
        [DataType(DataType.Date)]
        public DateTime? StartTime { get; set; }

        [Display(Name = "End time")]
        [DataType(DataType.Date)]
        public DateTime? EndTime { get; set; }

        [Display(Name = "Result")]
        public string Result { get; set; }

        public override string ToString()
        {
            return string.Format("Id: {0} \n" +
                                 "Template: {1} \n" +
                                 "Data: {2} \n" +
                                 "Owner: {3} \n" +
                                 "Result: {4}", Id, Template, Data, Owner, Result);
        }

        public string KeyString
        {
            get { return PartitionKey + "," + RowKey; }
        }
    }
}

MvcWebRole/Controllers/JobController.cs
using Microsoft.WindowsAzure.ServiceRuntime;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.RetryPolicies;
using Microsoft.WindowsAzure.Storage.Table;
using Microsoft.WindowsAzure.Storage.Table.DataServices;
using DocprocShared.Models;
using DocprocShared.QueueTask;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Linq.Expressions;
using DocprocShared.DataAccessLayer;
using Microsoft.WindowsAzure;
using Microsoft.WindowsAzure.Storage.Queue;

namespace MvcWebRole.Controllers
{
    public class JobController : Controller
    {

        private JobDAO jobDao;
        private CloudQueue workerQueue;

        public JobController()
        {
            this.jobDao = new JobDAO();
            CloudStorageAccount storageAccount = CloudStorageAccount.Parse(
                        CloudConfigurationManager.GetSetting("StorageConnectionString"));
            CloudQueueClient queueClient = storageAccount.CreateCloudQueueClient();
            workerQueue = queueClient.GetQueueReference("workerqueue");
            workerQueue.CreateIfNotExists();
        }

        public ActionResult Index()
        {
            string userName = System.Web.HttpContext.Current.User.Identity.Name;
            List<Job> jobsOfUser = jobDao.FindJobsOfUser(userName);
            return View(jobsOfUser);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(Job job)
        {
            job.Template = WebUtility.HtmlEncode(job.Template);
            job.PartitionKey = "USER-" + job.Owner;
            Trace.TraceInformation("created job: {0}", job);
            if (ModelState.IsValid)
            {
                Trace.TraceInformation("job is valid.");
                jobDao.PersistJob(job);
                
                CloudQueueMessage message = new CloudQueueMessage(new CsvToDataTask(job).ToBinary());
                workerQueue.AddMessage(message);
                return RedirectToAction("Index");
            }
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            return View(job);
        }

        public ActionResult Delete(string partitionKey, string rowKey)
        {
            var job = jobDao.FindJob(partitionKey, rowKey);
            return View(job);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string partitionKey, string rowKey)
        {
            jobDao.DeleteJob(partitionKey, rowKey);
            return RedirectToAction("Index");
        }

        public ActionResult Details(string partitionKey, string rowKey)
        {
            var job = jobDao.FindJob(partitionKey, rowKey);
            return View(job);
        }

    }
}

MvcWebRole/Controllers/TaskController.cs
using Microsoft.WindowsAzure.ServiceRuntime;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.RetryPolicies;
using Microsoft.WindowsAzure.Storage.Table;
using DocprocShared.DataAccessLayer;
using DocprocShared.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;
using DocprocShared.BlobAccessLayer;

namespace MvcWebRole.Controllers
{
    public class TaskController : Controller
    {

        private TaskDAO taskDao;
        private BlobAccess blobAccess;

        public TaskController()
        {
            taskDao = new TaskDAO();
            blobAccess = new BlobAccess();
        }

        public ActionResult Index(string jobPartitionKey, string jobRowKey)
        {
            JobDAO jobDAO = new JobDAO();
            Job job = jobDAO.FindJob(jobPartitionKey, jobRowKey);
            ViewBag.Job = job;
            return View(taskDao.FindTasksOfJob(job));
        }

        public ActionResult Delete(string partitionKey, string rowKey)
        {
            var task = taskDao.FindTask(partitionKey, rowKey);
            return View(task);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string partitionKey, string rowKey)
        {
            taskDao.DeleteTask(partitionKey, rowKey);
            return RedirectToAction("Index");
        }

        [ValidateInput(false)]
        public ActionResult Details(string partitionKey, string rowKey)
        {
            var task = taskDao.FindTask(partitionKey, rowKey);
            return View(task);
        }


        public static Expression<Func<Task, bool>> HasRowKeyPrefix(String prefix)
        {
            char lastChar = prefix[prefix.Length - 1];
            char nextLastChar = (char)((int)lastChar + 1);
            string nextPrefix = prefix.Substring(0, prefix.Length - 1) + nextLastChar;

            return e => e.RowKey.CompareTo(prefix) >= 0 && e.RowKey.CompareTo(nextPrefix) < 0;
        }
    }
}

MvcWebRole/Views/Job/Create.cshtml
@model DocprocShared.Models.Job

@{
    ViewBag.Title = "Create job";
}

@using Microsoft.AspNet.Identity
@using (Html.BeginForm("Create", "Job", FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()

        <h2>Add Job</h2>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Owner, new { @Value = User.Identity.GetUserName() })
        @Html.HiddenFor(model => model.Result)
        @Html.HiddenFor(model => model.StartTime)
        @Html.HiddenFor(model => model.EndTime)
    

        <label for="templateFile">
            Template file (HTML, UTF-8,
            reference data variables with ${variable}) <br />
            <a href="~/Content/example.html" download="example.html">Download example</a>
        </label> <input id="templateFile"
                        type="file" class="form-control" />
        <output class="collapse" id="outTemplate" for="template">
            <label for="Template">Template contents</label>
            <textarea class="form-control" id="Template" rows="10" cols="100" name="Template"></textarea>
        </output>
        <label for="dataFile">
            Data (CSV format, ';' seperator, UTF-8,
            header=variable names, rows=variable data)<br />
            Download example:
            <a href="~/Content/example-5.csv" download="example-5.csv">5 rows</a>
            <a href="~/Content/example-100.csv" download="example-100.csv">100 rows</a>
            <a href="~/Content/example-500.csv" download="example-500.csv">500 rows</a>
        </label> <input id="dataFile"
                        type="file" class="form-control" />
        <output id="outData" class="collapse" for="dataFile">
            <label for="summary">Summary</label>
            <ul id="summary" class="list-group">
                <li class="list-group-item">
                    <span class="toggler glyphicon glyphicon-chevron-down"
                          data-toggle="collapse" data-target="#variables"></span> <span id="variablesBadge" class="badge">0</span> Template variables
                </li>
                <div id="variables" class="collapse">
                    <ul id="variablesList"></ul>
                </div>
                <li class="list-group-item">
                    <span class="toggler glyphicon glyphicon-chevron-down"
                          data-toggle="collapse" data-target="#records"></span> <span id="recordsBadge" class="badge">0</span> Records
                </li>
                <div id="records" class="collapse">
                    <ul id="recordsList"></ul>
                </div>
            </ul>
            <label for="Data">CSV data contents</label>
            <textarea class="form-control" id="Data" rows="10" cols="100"
                      name="Data"></textarea>
        </output>
        <hr />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
}

<div>
    @Html.ActionLink("Job History", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript" src="@Url.Content("/Scripts/docproc.js")"> </script>
    <script type="text/javascript" src="@Url.Content("/Scripts/jquery.csv-0.71.js")"> </script>
}

MvcWebRole/Views/Job/Delete.cshtml
@model DocprocShared.Models.Job

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Job @Html.DisplayFor(model => model.Id)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Template)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Template)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Owner)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Owner)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Result)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Result)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MvcWebRole/Views/Job/Details.cshtml
@model DocprocShared.Models.Job
@using DocprocShared.BlobAccessLayer;
@{
    var blobAccess = new BlobAccess();
}

<div>
    <h4>Job @Html.DisplayFor(model => model.Id)</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Template)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Template)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Owner)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Owner)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @if (Model.StartTime != null)
            {
                @Html.DisplayFor(model => model.StartTime);
            }
            else
            {
                @:N/A (In queue)
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @if (Model.EndTime != null)
            {
                @Html.DisplayFor(modelItem => Model.EndTime)
            }
            else
            {
                @:N/A (Not finished yet)
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Result)
        </dt>

        <dd>
            @if (Model.Result != null)
            {
                <a href="@blobAccess.GetSASUri(Model, 15)" download="@String.Concat(Model.RowKey,".zip")">Download</a>
            }
            else
            {
                @:N/A (Not finished yet)
            }
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Delete", "Delete", new { partitionKey = Model.PartitionKey, rowKey = Model.RowKey }) |
    @Html.ActionLink("Show Tasks", "Index", "Task", new { jobPartitionKey = Model.PartitionKey, jobRowKey = Model.RowKey }, null) |
    @Html.ActionLink("Back to List", "Index")
</p>

MvcWebRole/Views/Job/Index.cshtml
@model IEnumerable<DocprocShared.Models.Job>
@using Microsoft.AspNet.Identity
@using DocprocShared.BlobAccessLayer;
@{
    ViewBag.Title = "Jobs";
    var blobAccess = new BlobAccess();
 }

<h2>Jobs for @User.Identity.GetUserName()</h2>

<table class="table table-striped table-bordered table-condensed">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RowKey)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Result)
        </th>
        <th>Actions</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RowKey)
            </td>
            <td>
                @if (item.StartTime != null)
                {
                    @Html.DisplayFor(modelItem => item.StartTime);
                }
                else
                {
                    @:N/A (In queue)
                }
                
            </td>
            <td>
                @if(item.EndTime != null){
                   @Html.DisplayFor(modelItem => item.EndTime)
                }
                else{
                    @:N/A (Not finished yet)
                }
            </td>
            <td>
                @if (item.Result != null)
                {
                    <a href="@blobAccess.GetSASUri(item, 15)" download="@String.Concat(item.RowKey,".zip")">Download</a>
                }
                else
                {
                    @:N/A (Not finished yet)
                }
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { PartitionKey = item.PartitionKey, RowKey=item.RowKey }) |
                @Html.ActionLink("Delete", "Delete", new { PartitionKey = item.PartitionKey, RowKey=item.RowKey })
            </td>
        </tr>
    }

</table>